language: node_js
node_js: node
dist: trusty
os:
- linux
- osx
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y devscripts build-essential lintian dh-make libxtst-dev libxkbfile-dev rpm; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install node; fi
install:
- npm i -g npm@5.2
- npm install
- cd app/ && npm install && cd ..
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf rpmbuild/; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir -p rpmbuild/SOURCES && tar -cjf rpmbuild/SOURCES/dummy.tar.bz2 readme.md; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build:osx; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build:linux; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then debuild -b -uc -us; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build:linuxarmv7l; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then debuild -b -uc -us -aarmhf; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd rpmbuild && rpmbuild --define "_topdir $(pwd)/" -bb ../whatsapp-desktop.spec && cd ..; fi
before_deploy:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y zip tar gzip; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install zip; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd dist/ && tar czf WhatsApp-linux-x64.tar.gz WhatsApp-linux-x64/ && tar czf WhatsApp-linux-armv7l.tar.gz WhatsApp-linux-armv7l/ && cd ..; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd dist/ && zip -r WhatsApp-darwin-x64.zip WhatsApp-darwin-x64/ && cd ..; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RELEASE_AMD64_PKG_FILE=$(ls ../whatsapp-desktop*amd64.deb); fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RELEASE_ARM_PKG_FILE=$(ls ../whatsapp-desktop*armhf.deb); fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RELEASE_AMD64_RPM_FILE=$(ls rpmbuild/RPMS/x86_64/*.rpm); fi
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
  file_glob: true
  file:
  - dist/WhatsApp-darwin-x64.zip
  - dist/WhatsApp-linux-x64.tar.gz
  - dist/WhatsApp-linux-armv7l.tar.gz
  - "${RELEASE_AMD64_PKG_FILE}"
  - "${RELEASE_ARM_PKG_FILE}"
  - "${RELEASE_AMD64_RPM_FILE}"
  api_key:
    secure: TX/psfzZ+R8Ua7y/uWUSFLVzajfANM/flNyDO5bG9X/LqURoWOQEnjmvUYV4xBp9IJM/xc5/icvUfl2DyNPunmZdRtVv0M85JhkKkQ0wywGhSHENo33kAWDn9v9gFb5w/cRpkghHOYUH9C7GLSulVxtuyb4FacrvvUdqr6kcth9gzWAqG3MBJNID+sI0/JooyGdu2VTMaszlImyzM4m76UQVl9K09ZCQbtoSlnVGYBhkMbu13gh750LWFbdf02KUkEO3TxQ8WYRMJ1VaXy0j/qcCi3mFAQxWxwvvxDrayNuZPoqLcfp0FFJLtqwT+QIaCPHpWwUWiiAHpLWNj/OmzEk7NkmTkKJ44ToBnJgAs3KibEvS+qrXdUO9qOWYUFG27EkCjQSppSWtZmn9EkY4BilSp6lFL8fPQWcjzvT7tkoQUs//g+cgyYHu5t3fgT3Ld1FuSkbpCzixxwbfWzUnR+jco0aWmtAT6f1wpbHmWAWEUI12SNEy8BtnvyZdXCGIYJFD7vJEM9i8NoT/ztvW1uXq7zqN8IZAFYt6BwmgHSWJ/KKsvaD9itOApVJCWEZy/JH7bm/7iE1z9KjWfUelfIwLAc1VJ5HHtEVfeLdz1oCwQ/WXSPeasQuMPqxrBFgHteyz6zdg1cgY3BoiLMZFpyaafYKdLYpDS9pS7rTuvuM=
