language: node_js
node_js: node
dist: trusty
os:
- linux
- osx
before_install:
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && sudo apt-get update
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && sudo apt-get install -y devscripts build-essential lintian dh-make rpm
- [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew update && brew install node
install:
- npm i -g npm@5.2
- npm install
- cd app/ && npm install && cd ..
before_script:
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && rm -rf rpmbuild/
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && mkdir -p rpmbuild/SOURCES
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && tar -cjf rpmbuild/SOURCES/dummy.tar.bz2 readme.md
script:
- [[ "$TRAVIS_OS_NAME" == "osx" ]] && npm run build:osx
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && npm run build:linux
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && debuild -b -uc -us
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && npm run build:linuxarmv7l
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && debuild -b -uc -us -aarmhf
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && cd rpmbuild && rpmbuild --define "_topdir $(pwd)/" -bb ../whatsapp-desktop.spec && cd ..
before_deploy:
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && sudo apt-get install -y zip tar gzip
- [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew install zip
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && cd dist/ && tar czf WhatsApp-linux-x64.tar.gz WhatsApp-linux-x64/ && tar czf WhatsApp-linux-armv7l.tar.gz WhatsApp-linux-armv7l/ && cd ..
- [[ "$TRAVIS_OS_NAME" == "osx" ]] && cd dist/ && zip -r WhatsApp-darwin-x64.zip WhatsApp-darwin-x64/ && cd ..
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && export RELEASE_AMD64_PKG_FILE=$(ls ../whatsapp-desktop*amd64.deb)
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && export RELEASE_ARM_PKG_FILE=$(ls ../whatsapp-desktop*armhf.deb)
- [[ "$TRAVIS_OS_NAME" == "linux" ]] && export RELEASE_AMD64_RPM_FILE=$(ls rpmbuild/RPMS/x86_64/*.rpm)
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
  file_glob: true
  file:
  - dist/WhatsApp-darwin-x64.zip
  - dist/WhatsApp-linux-x64.tar.gz
  - dist/WhatsApp-linux-armv7l.tar.gz
  - "${RELEASE_AMD64_PKG_FILE}"
  - "${RELEASE_ARM_PKG_FILE}"
  - "${RELEASE_AMD64_RPM_FILE}"
  api_key:
    secure: TX/psfzZ+R8Ua7y/uWUSFLVzajfANM/flNyDO5bG9X/LqURoWOQEnjmvUYV4xBp9IJM/xc5/icvUfl2DyNPunmZdRtVv0M85JhkKkQ0wywGhSHENo33kAWDn9v9gFb5w/cRpkghHOYUH9C7GLSulVxtuyb4FacrvvUdqr6kcth9gzWAqG3MBJNID+sI0/JooyGdu2VTMaszlImyzM4m76UQVl9K09ZCQbtoSlnVGYBhkMbu13gh750LWFbdf02KUkEO3TxQ8WYRMJ1VaXy0j/qcCi3mFAQxWxwvvxDrayNuZPoqLcfp0FFJLtqwT+QIaCPHpWwUWiiAHpLWNj/OmzEk7NkmTkKJ44ToBnJgAs3KibEvS+qrXdUO9qOWYUFG27EkCjQSppSWtZmn9EkY4BilSp6lFL8fPQWcjzvT7tkoQUs//g+cgyYHu5t3fgT3Ld1FuSkbpCzixxwbfWzUnR+jco0aWmtAT6f1wpbHmWAWEUI12SNEy8BtnvyZdXCGIYJFD7vJEM9i8NoT/ztvW1uXq7zqN8IZAFYt6BwmgHSWJ/KKsvaD9itOApVJCWEZy/JH7bm/7iE1z9KjWfUelfIwLAc1VJ5HHtEVfeLdz1oCwQ/WXSPeasQuMPqxrBFgHteyz6zdg1cgY3BoiLMZFpyaafYKdLYpDS9pS7rTuvuM=
